<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>scopeName</key>
        <string>source.edk2</string>
        <key>uuid</key>
        <string>A03D8E99-E2EF-4C67-A919-6AA2C5FF8155</string>
        <key>fileTypes</key>
        <array>
            <string>dec</string>
            <string>dsc</string>
        </array>
        <key>name</key>
        <string>edk2</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>keyword.control.dec</string>
                <key>match</key>
                <string>\b(if|while|for|return)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.line.dec</string>
                <key>begin</key>
                <string>#</string>
                <key>end</key>
                <string>\n</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.dec</string>
                <key>match</key>
                <string>(\[)(.*?)(\])</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\s\s[A-Z_].*\s)(=)(\s\S*)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.dec</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>([A-Za-z].*)(\.)([A-Za-z].*)(\|)(.*)(\|)(.*)(\|)(.*)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.dec</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.dec</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                    <key>7</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                    <key>9</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>(\s\s\w.*)(=)(\s\{)(.*\s)(\})</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.dec</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>(.*)(\|)(.*.h)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.dec</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>(.*)(\|)(.*.inf)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.dec</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>comment.line.dec</string>
                    </dict>
                </dict>
            </dict>
        </array>
    <key>repository</key>
    <dict>
        
    </dict>
</dict>
</plist>